"""
Question bank for daily questions and profile enrichment.
50+ questions across all categories with i18n support.
"""

QUESTION_BANK = [
    # ============================================================
    # NETWORKING (10 questions)
    # ============================================================
    {
        "id": "net_dream_collab",
        "category": "networking",
        "intents": ["networking"],
        "priority": 1,
        "depth": "medium",
        "text_en": "If you could collaborate with anyone in the world, who and why?",
        "text_ru": "Если бы ты мог коллаборировать с кем угодно в мире, с кем и почему?",
        "extracts": ["goals", "interests", "looking_for"],
    },
    {
        "id": "net_superpower",
        "category": "networking",
        "intents": ["networking"],
        "priority": 2,
        "depth": "light",
        "text_en": "What's your professional superpower — the thing people always come to you for?",
        "text_ru": "Какая твоя профессиональная суперсила — то, за чем к тебе всегда обращаются?",
        "extracts": ["can_help_with", "skills"],
    },
    {
        "id": "net_learn_skill",
        "category": "networking",
        "intents": ["networking"],
        "priority": 3,
        "depth": "light",
        "text_en": "What skill would you love to learn from someone this year?",
        "text_ru": "Какой навык ты хотел бы перенять у кого-то в этом году?",
        "extracts": ["looking_for", "interests"],
    },
    {
        "id": "net_project_excited",
        "category": "networking",
        "intents": ["networking"],
        "priority": 2,
        "depth": "medium",
        "text_en": "What project or idea are you most excited about right now?",
        "text_ru": "Какой проект или идея тебя сейчас больше всего вдохновляет?",
        "extracts": ["bio", "interests", "goals"],
    },
    {
        "id": "net_industry_change",
        "category": "networking",
        "intents": ["networking"],
        "priority": 4,
        "depth": "deep",
        "text_en": "What's one thing you'd change about your industry if you could?",
        "text_ru": "Что бы ты изменил в своей индустрии, если бы мог?",
        "extracts": ["interests", "goals"],
    },
    {
        "id": "net_best_advice",
        "category": "networking",
        "intents": ["networking"],
        "priority": 3,
        "depth": "medium",
        "text_en": "What's the best professional advice you've ever received?",
        "text_ru": "Какой лучший профессиональный совет ты получал?",
        "extracts": ["bio", "can_help_with"],
    },
    {
        "id": "net_side_project",
        "category": "networking",
        "intents": ["networking"],
        "priority": 2,
        "depth": "light",
        "text_en": "Working on any side projects or passion projects?",
        "text_ru": "Работаешь над каким-то сайд-проектом или проектом по душе?",
        "extracts": ["interests", "skills", "goals"],
    },
    {
        "id": "net_mentor",
        "category": "networking",
        "intents": ["networking"],
        "priority": 4,
        "depth": "deep",
        "text_en": "Have you had a mentor who changed your path? What did they teach you?",
        "text_ru": "Был ли у тебя ментор, который изменил твой путь? Чему он тебя научил?",
        "extracts": ["bio", "looking_for"],
    },
    {
        "id": "net_5years",
        "category": "networking",
        "intents": ["networking"],
        "priority": 5,
        "depth": "deep",
        "text_en": "Where do you see yourself in 5 years? Big dreams welcome.",
        "text_ru": "Где ты видишь себя через 5 лет? Большие мечты приветствуются.",
        "extracts": ["goals", "bio"],
    },
    {
        "id": "net_event_takeaway",
        "category": "networking",
        "intents": ["networking"],
        "priority": 3,
        "depth": "light",
        "text_en": "What's the best thing that happened to you from a random networking conversation?",
        "text_ru": "Что лучшее произошло у тебя из случайного нетворкинг-разговора?",
        "extracts": ["looking_for", "goals"],
    },

    # ============================================================
    # FRIENDS (10 questions)
    # ============================================================
    {
        "id": "fr_perfect_weekend",
        "category": "friends",
        "intents": ["friends"],
        "priority": 1,
        "depth": "light",
        "text_en": "Describe your perfect weekend in 3 words.",
        "text_ru": "Опиши своё идеальное выходные в 3 словах.",
        "extracts": ["interests", "personality_vibe"],
    },
    {
        "id": "fr_guilty_pleasure",
        "category": "friends",
        "intents": ["friends"],
        "priority": 2,
        "depth": "light",
        "text_en": "What's your guilty pleasure that you'd never put on a resume?",
        "text_ru": "Какое у тебя виноватое удовольствие, которое никогда не попадёт в резюме?",
        "extracts": ["interests", "personality_vibe"],
    },
    {
        "id": "fr_learn_overnight",
        "category": "friends",
        "intents": ["friends", "networking"],
        "priority": 1,
        "depth": "light",
        "text_en": "If you could learn any skill overnight, what would it be and why?",
        "text_ru": "Если бы ты мог выучить любой навык за ночь, что бы это было и почему?",
        "extracts": ["interests", "goals"],
    },
    {
        "id": "fr_travel_dream",
        "category": "friends",
        "intents": ["friends"],
        "priority": 3,
        "depth": "medium",
        "text_en": "If you could live anywhere for a year, where would you go?",
        "text_ru": "Если бы ты мог жить где угодно год, куда бы поехал?",
        "extracts": ["interests", "personality_vibe"],
    },
    {
        "id": "fr_last_obsession",
        "category": "friends",
        "intents": ["friends"],
        "priority": 2,
        "depth": "light",
        "text_en": "What's the last thing you got completely obsessed with?",
        "text_ru": "Чем ты последний раз полностью увлёкся?",
        "extracts": ["interests"],
    },
    {
        "id": "fr_friend_type",
        "category": "friends",
        "intents": ["friends"],
        "priority": 1,
        "depth": "medium",
        "text_en": "What kind of friend are you? The planner, the spontaneous one, the listener?",
        "text_ru": "Какой ты друг? Планировщик, спонтанный, слушатель?",
        "extracts": ["personality_vibe", "looking_for"],
    },
    {
        "id": "fr_unpopular_opinion",
        "category": "friends",
        "intents": ["friends"],
        "priority": 3,
        "depth": "light",
        "text_en": "Share an unpopular opinion you actually believe in.",
        "text_ru": "Расскажи непопулярное мнение, в которое реально веришь.",
        "extracts": ["personality_vibe", "interests"],
    },
    {
        "id": "fr_concert",
        "category": "friends",
        "intents": ["friends"],
        "priority": 4,
        "depth": "light",
        "text_en": "Last concert, movie, or show that blew your mind?",
        "text_ru": "Последний концерт, фильм или шоу, которое тебя поразило?",
        "extracts": ["interests"],
    },
    {
        "id": "fr_cooking",
        "category": "friends",
        "intents": ["friends"],
        "priority": 4,
        "depth": "light",
        "text_en": "What's the one dish you cook that always impresses people?",
        "text_ru": "Какое блюдо ты готовишь, которое всегда впечатляет?",
        "extracts": ["interests", "skills"],
    },
    {
        "id": "fr_recharge",
        "category": "friends",
        "intents": ["friends"],
        "priority": 2,
        "depth": "medium",
        "text_en": "How do you recharge after a long week? Solo time or social energy?",
        "text_ru": "Как ты восстанавливаешься после тяжёлой недели? Одиночество или общение?",
        "extracts": ["personality_vibe"],
    },

    # ============================================================
    # ROMANCE (10 questions)
    # ============================================================
    {
        "id": "rom_love_language",
        "category": "romance",
        "intents": ["romance"],
        "priority": 1,
        "depth": "medium",
        "text_en": "What's your love language — how do you show someone you care?",
        "text_ru": "Какой твой язык любви — как ты показываешь заботу?",
        "extracts": ["partner_values", "personality_vibe"],
    },
    {
        "id": "rom_ideal_date",
        "category": "romance",
        "intents": ["romance", "hookup"],
        "priority": 1,
        "depth": "light",
        "text_en": "Describe your ideal date — keep it real, not movie-perfect.",
        "text_ru": "Опиши идеальное свидание — реальное, не из фильма.",
        "extracts": ["interests", "hookup_preference"],
    },
    {
        "id": "rom_dealbreaker",
        "category": "romance",
        "intents": ["romance"],
        "priority": 2,
        "depth": "medium",
        "text_en": "What's a relationship deal-breaker for you that might surprise people?",
        "text_ru": "Какой у тебя deal-breaker в отношениях, который может удивить?",
        "extracts": ["partner_values"],
    },
    {
        "id": "rom_attracted_to",
        "category": "romance",
        "intents": ["romance"],
        "priority": 2,
        "depth": "medium",
        "text_en": "What non-physical trait do you find most attractive in a person?",
        "text_ru": "Какая нефизическая черта тебя больше всего привлекает в человеке?",
        "extracts": ["partner_values", "looking_for"],
    },
    {
        "id": "rom_relationship_lesson",
        "category": "romance",
        "intents": ["romance"],
        "priority": 3,
        "depth": "deep",
        "text_en": "What's the most important lesson you've learned from past relationships?",
        "text_ru": "Какой самый важный урок ты вынес из прошлых отношений?",
        "extracts": ["partner_values", "bio"],
    },
    {
        "id": "rom_morning_person",
        "category": "romance",
        "intents": ["romance", "hookup"],
        "priority": 3,
        "depth": "light",
        "text_en": "Are you a morning person or a night owl? This matters more than people think.",
        "text_ru": "Ты жаворонок или сова? Это важнее, чем кажется.",
        "extracts": ["personality_vibe"],
    },
    {
        "id": "rom_together_activity",
        "category": "romance",
        "intents": ["romance"],
        "priority": 2,
        "depth": "light",
        "text_en": "What's something you'd love to do with a partner that you've never tried?",
        "text_ru": "Что бы ты хотел попробовать с партнёром, но ещё не пробовал?",
        "extracts": ["interests", "looking_for"],
    },
    {
        "id": "rom_home_vs_adventure",
        "category": "romance",
        "intents": ["romance"],
        "priority": 4,
        "depth": "light",
        "text_en": "Cozy night in or spontaneous adventure? What's your default mode?",
        "text_ru": "Уютный вечер дома или спонтанное приключение? Какой у тебя режим по умолчанию?",
        "extracts": ["personality_vibe", "hookup_preference"],
    },
    {
        "id": "rom_communicate",
        "category": "romance",
        "intents": ["romance"],
        "priority": 3,
        "depth": "medium",
        "text_en": "How do you handle disagreements — talk it out immediately or take space first?",
        "text_ru": "Как ты решаешь разногласия — сразу обсуждаешь или берёшь паузу?",
        "extracts": ["personality_vibe", "partner_values"],
    },
    {
        "id": "rom_future_vision",
        "category": "romance",
        "intents": ["romance"],
        "priority": 5,
        "depth": "deep",
        "text_en": "What does your ideal life look like in 10 years? Paint the picture.",
        "text_ru": "Как выглядит твоя идеальная жизнь через 10 лет? Нарисуй картину.",
        "extracts": ["goals", "partner_values", "bio"],
    },

    # ============================================================
    # HOOKUP (5 questions)
    # ============================================================
    {
        "id": "hk_first_impression",
        "category": "hookup",
        "intents": ["hookup"],
        "priority": 1,
        "depth": "light",
        "text_en": "What's the first thing that catches your attention about someone at a bar or party?",
        "text_ru": "Что первое привлекает твоё внимание в человеке в баре или на вечеринке?",
        "extracts": ["looking_for", "hookup_preference"],
    },
    {
        "id": "hk_flirt_style",
        "category": "hookup",
        "intents": ["hookup"],
        "priority": 2,
        "depth": "light",
        "text_en": "What's your flirting style — direct, playful, mysterious, or slow burn?",
        "text_ru": "Какой твой стиль флирта — прямой, игривый, загадочный или медленное горение?",
        "extracts": ["personality_vibe", "hookup_preference"],
    },
    {
        "id": "hk_spontaneous",
        "category": "hookup",
        "intents": ["hookup"],
        "priority": 2,
        "depth": "light",
        "text_en": "Most spontaneous thing you've ever done on a date?",
        "text_ru": "Самое спонтанное, что ты делал на свидании?",
        "extracts": ["personality_vibe", "interests"],
    },
    {
        "id": "hk_vibe_check",
        "category": "hookup",
        "intents": ["hookup"],
        "priority": 1,
        "depth": "light",
        "text_en": "Late-night rooftop drinks or early morning coffee date — what's your energy?",
        "text_ru": "Поздние коктейли на крыше или утренний кофе — какая у тебя энергия?",
        "extracts": ["hookup_preference", "personality_vibe"],
    },
    {
        "id": "hk_chemistry",
        "category": "hookup",
        "intents": ["hookup"],
        "priority": 3,
        "depth": "medium",
        "text_en": "What creates chemistry for you — conversation, humor, confidence, or something else?",
        "text_ru": "Что создаёт для тебя химию — разговор, юмор, уверенность, или что-то другое?",
        "extracts": ["partner_values", "looking_for"],
    },

    # ============================================================
    # SELF-DISCOVERY (8 questions)
    # ============================================================
    {
        "id": "sd_proudest",
        "category": "self_discovery",
        "intents": ["networking", "friends", "romance"],
        "priority": 3,
        "depth": "deep",
        "text_en": "What's something you're genuinely proud of that has nothing to do with work?",
        "text_ru": "Чем ты гордишься, что не связано с работой?",
        "extracts": ["bio", "interests"],
    },
    {
        "id": "sd_values",
        "category": "self_discovery",
        "intents": ["networking", "friends", "romance"],
        "priority": 2,
        "depth": "deep",
        "text_en": "What's one value you'd never compromise on, no matter what?",
        "text_ru": "Какую ценность ты бы никогда не предал, что бы ни случилось?",
        "extracts": ["partner_values", "personality_vibe"],
    },
    {
        "id": "sd_childhood_dream",
        "category": "self_discovery",
        "intents": ["friends", "romance"],
        "priority": 4,
        "depth": "medium",
        "text_en": "What did you want to be when you grew up? How close are you now?",
        "text_ru": "Кем ты хотел стать в детстве? Насколько близко ты сейчас?",
        "extracts": ["bio", "goals"],
    },
    {
        "id": "sd_life_motto",
        "category": "self_discovery",
        "intents": ["networking", "friends"],
        "priority": 3,
        "depth": "medium",
        "text_en": "If you had a personal motto, what would it be?",
        "text_ru": "Если бы у тебя был личный девиз, какой бы он был?",
        "extracts": ["personality_vibe", "bio"],
    },
    {
        "id": "sd_fear",
        "category": "self_discovery",
        "intents": ["friends", "romance"],
        "priority": 5,
        "depth": "deep",
        "text_en": "What's something you're afraid of that you're working on overcoming?",
        "text_ru": "Чего ты боишься и над чем работаешь, чтобы преодолеть?",
        "extracts": ["personality_vibe", "goals"],
    },
    {
        "id": "sd_change_mind",
        "category": "self_discovery",
        "intents": ["networking", "friends", "romance"],
        "priority": 3,
        "depth": "medium",
        "text_en": "What's a belief you held strongly that you've completely changed your mind about?",
        "text_ru": "В чём ты был сильно убеждён, но полностью изменил мнение?",
        "extracts": ["personality_vibe", "interests"],
    },
    {
        "id": "sd_energy_source",
        "category": "self_discovery",
        "intents": ["friends", "romance"],
        "priority": 2,
        "depth": "light",
        "text_en": "What gives you energy — people, solitude, nature, creating, or moving?",
        "text_ru": "Что даёт тебе энергию — люди, одиночество, природа, творчество или движение?",
        "extracts": ["personality_vibe"],
    },
    {
        "id": "sd_grateful",
        "category": "self_discovery",
        "intents": ["friends", "romance"],
        "priority": 4,
        "depth": "medium",
        "text_en": "What's something small that always makes your day better?",
        "text_ru": "Что маленькое всегда делает твой день лучше?",
        "extracts": ["interests", "personality_vibe"],
    },

    # ============================================================
    # ICEBREAKERS (10 questions)
    # ============================================================
    {
        "id": "ice_dinner_party",
        "category": "icebreaker",
        "intents": ["networking", "friends", "romance", "hookup"],
        "priority": 1,
        "depth": "light",
        "text_en": "You're hosting a dinner for 4 people — anyone alive. Who's coming?",
        "text_ru": "Ты устраиваешь ужин на 4 человека — кого угодно из живых. Кого позовёшь?",
        "extracts": ["interests", "personality_vibe"],
    },
    {
        "id": "ice_time_travel",
        "category": "icebreaker",
        "intents": ["networking", "friends", "romance", "hookup"],
        "priority": 1,
        "depth": "light",
        "text_en": "Time machine: would you go to the past or the future? Where exactly?",
        "text_ru": "Машина времени: в прошлое или будущее? Куда именно?",
        "extracts": ["interests", "personality_vibe"],
    },
    {
        "id": "ice_desert_island",
        "category": "icebreaker",
        "intents": ["friends", "romance", "hookup"],
        "priority": 2,
        "depth": "light",
        "text_en": "Desert island: one book, one album, one luxury item. Go.",
        "text_ru": "Необитаемый остров: одна книга, один альбом, одна роскошь. Давай.",
        "extracts": ["interests"],
    },
    {
        "id": "ice_superpower",
        "category": "icebreaker",
        "intents": ["friends", "hookup"],
        "priority": 2,
        "depth": "light",
        "text_en": "If you had one superpower, what would you choose and what's the first thing you'd do?",
        "text_ru": "Если бы у тебя была суперсила, что бы выбрал и что сделал первым делом?",
        "extracts": ["personality_vibe"],
    },
    {
        "id": "ice_this_or_that_1",
        "category": "icebreaker",
        "intents": ["friends", "romance", "hookup"],
        "priority": 1,
        "depth": "light",
        "text_en": "Quick picks: Mountains or beach? 🏔️ or 🏖️",
        "text_ru": "Быстрый выбор: Горы или пляж? 🏔️ или 🏖️",
        "extracts": ["interests"],
    },
    {
        "id": "ice_this_or_that_2",
        "category": "icebreaker",
        "intents": ["friends", "romance", "hookup"],
        "priority": 1,
        "depth": "light",
        "text_en": "Would you rather: have the ability to fly or be invisible?",
        "text_ru": "Что бы ты выбрал: уметь летать или быть невидимым?",
        "extracts": ["personality_vibe"],
    },
    {
        "id": "ice_last_google",
        "category": "icebreaker",
        "intents": ["friends", "networking"],
        "priority": 2,
        "depth": "light",
        "text_en": "What's the last weird thing you googled? No judgment.",
        "text_ru": "Что последнее странное ты гуглил? Без осуждения.",
        "extracts": ["interests"],
    },
    {
        "id": "ice_billion_dollars",
        "category": "icebreaker",
        "intents": ["networking", "friends"],
        "priority": 3,
        "depth": "medium",
        "text_en": "You just got a billion dollars. What do you do first?",
        "text_ru": "Тебе только что дали миллиард долларов. Что делаешь первым делом?",
        "extracts": ["goals", "interests"],
    },
    {
        "id": "ice_alien",
        "category": "icebreaker",
        "intents": ["friends", "hookup"],
        "priority": 3,
        "depth": "light",
        "text_en": "An alien asks you to explain humanity in one sentence. What do you say?",
        "text_ru": "Инопланетянин просит объяснить человечество одним предложением. Что скажешь?",
        "extracts": ["personality_vibe"],
    },
    {
        "id": "ice_famous_for",
        "category": "icebreaker",
        "intents": ["networking", "friends"],
        "priority": 2,
        "depth": "light",
        "text_en": "If you could be famous for one thing, what would it be?",
        "text_ru": "Если бы ты мог быть знаменит за одну вещь, что бы это было?",
        "extracts": ["goals", "interests"],
    },
]
